name: nostr_client
description: A nostr client package.
homepage: https://github.com/UlrichRaab/nostr_client
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # https://pub.dev/packages/collection
  collection: ^1.17.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.7.0
  # https://pub.dev/packages/meta
  meta: ^1.8.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.5
  # https://pub.dev/packages/uuid
  uuid: ^3.0.6
  # https://pub.dev/packages/web_socket_channel
  web_socket_channel: ^2.2.0

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.2
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.5.4
  # https://pub.dev/packages/lints
  lints: ^2.0.1
  # https://pub.dev/packages/test
  test: ^1.21.7
