name: nostr_client
description: A nostr client package.
homepage: https://github.com/UlrichRaab/nostr_client
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # https://pub.dev/packages/collection
  collection: ^1.17.0
  # https://pub.dev/packages/meta
  meta: ^1.8.0
  # https://pub.dev/packages/path
  path: ^1.8.0
  # https://pub.dev/packages/web_socket_channel
  web_socket_channel: ^2.2.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^2.0.0
  # https://pub.dev/packages/test
  test: ^1.21.4
